
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cButton(object):
    def setupUi(self, cButton):
        cButton.setObjectName("cButton")
        cButton.resize(361, 588)
        self.centralwidget = QtWidgets.QWidget(cButton)
        self.centralwidget.setObjectName("centralwidget")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(10, 10, 341, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.outputLabel.setFont(font)
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.outputLabel.setLineWidth(3)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.percentButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("%"))
        self.percentButton.setGeometry(QtCore.QRect(10, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.percentButton.setFont(font)
        self.percentButton.setObjectName("percentButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("C"))
        self.pushButton_2.setGeometry(QtCore.QRect(100, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.arrowButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.remove_it())
        self.arrowButton.setGeometry(QtCore.QRect(190, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.arrowButton.setFont(font)
        self.arrowButton.setObjectName("arrowButton")
        self.divideButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("/"))
        self.divideButton.setGeometry(QtCore.QRect(275, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.divideButton.setFont(font)
        self.divideButton.setObjectName("divideButton")
        self.nineButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("9"))
        self.nineButton.setGeometry(QtCore.QRect(190, 190, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.nineButton.setFont(font)
        self.nineButton.setObjectName("nineButton")
        self.eightButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("8"))
        self.eightButton.setGeometry(QtCore.QRect(100, 190, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.eightButton.setFont(font)
        self.eightButton.setObjectName("eightButton")
        self.multiplyButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("*"))
        self.multiplyButton.setGeometry(QtCore.QRect(275, 190, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.multiplyButton.setFont(font)
        self.multiplyButton.setObjectName("multiplyButton")
        self.sevenButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("7"))
        self.sevenButton.setGeometry(QtCore.QRect(10, 190, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.sevenButton.setFont(font)
        self.sevenButton.setObjectName("sevenButton")
        self.sixButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("6"))
        self.sixButton.setGeometry(QtCore.QRect(190, 280, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.sixButton.setFont(font)
        self.sixButton.setObjectName("sixButton")
        self.fiveButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("5"))
        self.fiveButton.setGeometry(QtCore.QRect(100, 280, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.fiveButton.setFont(font)
        self.fiveButton.setObjectName("fiveButton")
        self.minusButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("-"))
        self.minusButton.setGeometry(QtCore.QRect(275, 280, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.minusButton.setFont(font)
        self.minusButton.setObjectName("minusButton")
        self.fourButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("4"))
        self.fourButton.setGeometry(QtCore.QRect(10, 280, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.fourButton.setFont(font)
        self.fourButton.setObjectName("fourButton")
        self.threeButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("3"))
        self.threeButton.setGeometry(QtCore.QRect(190, 370, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.threeButton.setFont(font)
        self.threeButton.setObjectName("threeButton")
        self.twoButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("2"))
        self.twoButton.setGeometry(QtCore.QRect(100, 370, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.twoButton.setFont(font)
        self.twoButton.setObjectName("twoButton")
        self.addButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("+"))
        self.addButton.setGeometry(QtCore.QRect(275, 370, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.oneButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("1"))
        self.oneButton.setGeometry(QtCore.QRect(10, 370, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.oneButton.setFont(font)
        self.oneButton.setObjectName("oneButton")
        self.decimalButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.dot_it())
        self.decimalButton.setGeometry(QtCore.QRect(190, 460, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.decimalButton.setFont(font)
        self.decimalButton.setObjectName("decimalButton")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.press_it("0"))
        self.zeroButton.setGeometry(QtCore.QRect(100, 460, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.zeroButton.setFont(font)
        self.zeroButton.setObjectName("zeroButton")
        self.equalButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.math_it())
        self.equalButton.setGeometry(QtCore.QRect(275, 460, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.equalButton.setFont(font)
        self.equalButton.setObjectName("equalButton")
        self.plusminusButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.plus_minus_it())
        self.plusminusButton.setGeometry(QtCore.QRect(10, 460, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.plusminusButton.setFont(font)
        self.plusminusButton.setObjectName("plusminusButton")
        cButton.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(cButton)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 21))
        self.menubar.setObjectName("menubar")
        cButton.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(cButton)
        self.statusbar.setObjectName("statusbar")
        cButton.setStatusBar(self.statusbar)

        self.retranslateUi(cButton)
        QtCore.QMetaObject.connectSlotsByName(cButton)

    def dot_it(self):
        screen = self.outputLabel.text()
        if screen[-1]=='.':
            pass
        else:
            self.outputLabel.setText(f'{screen}.')

    def remove_it(self):
        screen = self.outputLabel.text()
        screen = screen[:-1]
        self.outputLabel.setText(screen)

    def plus_minus_it(self):
        screen = self.outputLabel.text()
        if '-' in screen:
            self.outputLabel.setText(screen.replace('-',''))
        else:
            self.outputLabel.setText(f'-{screen}')

    def math_it(self):
        try:
            screen = self.outputLabel.text()
            answer = eval(screen)
            self.outputLabel.setText(str(answer))
        except:
            self.outputLabel.setText('ERROR')
    def press_it(self, pressed):
        if pressed == "C":
            self.outputLabel.setText("0")
        else:
            if self.outputLabel.text() == "0":
                self.outputLabel.setText("")
            self.outputLabel.setText(f'{self.outputLabel.text()}{pressed}')

    def retranslateUi(self, cButton):
        _translate = QtCore.QCoreApplication.translate
        cButton.setWindowTitle(_translate("cButton", "Calculator"))
        self.outputLabel.setText(_translate("cButton", "0"))
        self.percentButton.setText(_translate("cButton", "%"))
        self.pushButton_2.setText(_translate("cButton", "C"))
        self.arrowButton.setText(_translate("cButton", "<<"))
        self.divideButton.setText(_translate("cButton", "/"))
        self.nineButton.setText(_translate("cButton", "9"))
        self.eightButton.setText(_translate("cButton", "8"))
        self.multiplyButton.setText(_translate("cButton", "x"))
        self.sevenButton.setText(_translate("cButton", "7"))
        self.sixButton.setText(_translate("cButton", "6"))
        self.fiveButton.setText(_translate("cButton", "5"))
        self.minusButton.setText(_translate("cButton", "-"))
        self.fourButton.setText(_translate("cButton", "4"))
        self.threeButton.setText(_translate("cButton", "3"))
        self.twoButton.setText(_translate("cButton", "2"))
        self.addButton.setText(_translate("cButton", "+"))
        self.oneButton.setText(_translate("cButton", "1"))
        self.decimalButton.setText(_translate("cButton", "."))
        self.zeroButton.setText(_translate("cButton", "0"))
        self.equalButton.setText(_translate("cButton", "="))
        self.plusminusButton.setText(_translate("cButton", "+/-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cButton = QtWidgets.QMainWindow()
    ui = Ui_cButton()
    ui.setupUi(cButton)
    cButton.show()
    sys.exit(app.exec_())
